---
title: "Modélisation Bayésienne"
linktitle: "Modélisation Bayésienne"
date: "2020-11-30"
class_date: "2020-12-01"
menu:
  lectures:
    parent: "II Modélisation bayésienne"
    weight: 2
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "02-slides"
output:
  blogdown::html_page:
    toc: true
---

## Leçons vidéo


### Modélisation bayésienne partie 1
<iframe width="560" height="315" src="https://www.youtube.com/embed/Hy7hNrBo_Go" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Modélisation bayésienne partie 2
<iframe width="560" height="315" src="https://www.youtube.com/embed/Wc1bCLNA4Q8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


### Modélisation bayésienne partie 3
<iframe width="560" height="315" src="https://www.youtube.com/embed/c0yCMO-TwP0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


### Modélisation bayésienne --- *a priori*
<iframe width="560" height="315" src="https://www.youtube.com/embed/SH19H_W59Pc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

`r emo::ji("backhand index pointing right")` [*Shelf software*](http://www.tonyohagan.co.uk/shelf/)

`r emo::ji("backhand index pointing right")` [*SHELF `r icon::fa_r_project(colour = "#0085d6")` package*](http://www.tonyohagan.co.uk/shelf/)

### Modélisation bayésienne –-- extensions
<iframe width="560" height="315" src="https://www.youtube.com/embed/p67ql6pFZF8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


## Diaporamas

Le **diaporama** pour la première partie de cette section sont affichées ci-dessous, et peut être téléchargées [ici](/slides/slidesModel1.pdf).

<html>
<body>
  <object data="/slides/slidesModel1.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesModel1.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>


Le **diaporama** pour la deuxième partie de cette section sont affichées ci-dessous, et peut être téléchargées [ici](/slides/slidesModel2.pdf).

<html>
<body>
  <object data="/slides/slidesModel2.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesModel2.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>

Le **diaporama** pour la troisième partie de cette section sont affichées ci-dessous, et peut être téléchargées [ici](/slides/slidesModel3.pdf).

<html>
<body>
  <object data="/slides/slidesModel3.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesModel3.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>

Le **diaporama** pour la quatrième partie de cette section sont affichées ci-dessous, et peut être téléchargées [ici](/slides/slidesModel4.pdf).

<html>
<body>
  <object data="/slides/slidesModel4.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesModel4.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>

Le **diaporama** pour la cinquième partie de cette section sont affichées ci-dessous, et peut être téléchargées [ici](/slides/slidesPriors.pdf).

<html>
<body>
  <object data="/slides/slidesPriors.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesPriors.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>

Le **diaporama** pour la sixième partie de cette section sont affichées ci-dessous, et peut être téléchargées [ici](/slides/slidesGoingFurther.pdf).

<html>
<body>
  <object data="/slides/slidesGoingFurther.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesGoingFurther.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>