---
title: "Inférence bayésienne"
linktitle: "Inférence bayésienne"
date: "2020-11-30"
class_date: "2020-12-01"
menu:
  lectures:
    parent: "II Modélisation bayésienne"
    weight: 3
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "02-slides"
output:
  blogdown::html_page:
    toc: true
---

## Leçons video


### Inférence Bayésienne partie 1: estimateur ponctuels
<iframe width="560" height="315" src="https://www.youtube.com/embed/jYhctgHLs9A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Inférence Bayésienne partie 2: MAP
<iframe width="560" height="315" src="https://www.youtube.com/embed/K8SDbqXAsb8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Inférence Bayésienne partie 3: espérance
<iframe width="560" height="315" src="https://www.youtube.com/embed/7u5KokmXOHE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Inférence Bayésienne partie 4: incertitude
<iframe width="560" height="315" src="https://www.youtube.com/embed/4E7p5T4rLKM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


### Inférence Bayésienne --- asymptotique
<iframe width="560" height="315" src="https://www.youtube.com/embed/RdhyuOl17OM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

`r emo::ji("backhand index pointing right")` [*Seeing Theory*, Brown University](http://students.brown.edu/seeing-theory/bayesian-inference/index.html\#section3)

## Diaporamas

Le **diaporama** pour la première partie de cette section sont affichées ci-dessous, et peuvent être téléchargées [ici](/slides/slidesInference.pdf).

<html>
<body>
  <object data="/slides/slidesInference.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesInference.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>

Le **diaporama** pour la deuxième partie de cette section sont affichées ci-dessous, et peuvent être téléchargées [ici](/slides/slidesUncertainty.pdf).

<html>
<body>
  <object data="/slides/slidesUncertainty.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesUncertainty.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>

Le **diaporama** pour la troisième partie de cette section sont affichées ci-dessous, et peuvent être téléchargées [ici](/slides/slidesAsymptotics.pdf).

<html>
<body>
  <object data="/slides/slidesAsymptotics.pdf##view=fit" type="application/pdf" width="420" height="237">
        <embed src="/slides/slidesAsymptotics.pdf##view=fit" type="application/pdf"/>
  </object>
</body>
</html>
