---
title: "Exercice 2"
linktitle: "Exercice 2"
date: "2020-11-30"
exo_date: "2020-12-02"
menu:
  td:
    parent: "TD"
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: false
    number_sections: false
bibliography: "../../static/bib/references.bib"
---

```{r, include=FALSE}
correction <-  FALSE # TRUE #
knitr::opts_chunk$set(tidy = TRUE, message = FALSE, cache=TRUE)
if(knitr::opts_knit$get("rmarkdown.pandoc.to") == "latex"){
  knitr::opts_chunk$set(tidy = TRUE, message = FALSE, tidy.opts=list(width.cutoff=45), 
                        dev="pdf", fig.align="center")
  correction <-  FALSE
}
#"`r gsub(' 0', ' ', format.Date(Sys.Date(), '%B %dth, %Y'))`"
```

\noindent On considère les réalisations $\boldsymbol{x} = \{x_1,\ldots,x_n\}$ d'une suite de variables aléatoires $iid$ $\{X_i\}_{i=1, \dots, n}$ positives suivant une loi exponentielle de paramètre $\lambda$ : $\mathcal{E}(\lambda)$,
où $\lambda>0$ est inconnu et on cherche à l'estimer. 

On rappelle la densité de probabilité pour la distribution exponentielle : $f_\lambda(x) = \lambda e^{-\lambda x}$ pour $x>0$. 

On utilise comme loi *a priori* sur $\lambda$ la loi Gamma $\mathcal G(\alpha,\beta)$ dont la densité s'écrit :
$$ g(\lambda) = \lambda^{\alpha-1} \frac{\beta^\alpha e^{-\beta \lambda}}{\Gamma(\alpha)}$$

 1. Écrire est le modèle bayésien associé.
 
:::Correction
  1. **Question d'intérêt**  
 Elle porte ici sur l'estimation de $\lambda$.
 
 2. **Modèle d'échantillonnage**
 $$X_i\overset{iid}{\sim} \mathcal{E}(\lambda)$$
 et donc $\displaystyle f_{\sigma^2}(x_i|\lambda) = \lambda e^{-\lambda x_i}$
 
 3. **loi(s) *a priori***
 $$\lambda\sim\mathcal G(\alpha,\beta)$$
 ($\alpha$ et $\beta$ --- les hyperparamètres --- sont considérés connus).
:::
<br>

 
	
 2. Pouvez-vous identifiez la loi *a posteriori* correspondante ?
 
:::Correction
D'après le théorème de Bayes, le numérateur de la loi *a posteriori* s'écrit :
\begin{align*}
  p(\lambda | \boldsymbol{x}) &\propto f(x_1, \dots, x_n | \lambda)g(\lambda)\\
  &\propto \prod_{i=1}^n \lambda e^{-\lambda x_i} \lambda^{\alpha-1} \frac{\beta^\alpha e^{-\beta \lambda}}{\Gamma(\alpha)}\\
  &\propto \lambda^n e^{-\lambda \sum_{i=1}^n x_i} \lambda^{\alpha-1} e^{-\beta \lambda}\\
  &\propto \lambda^{\alpha + n -1} e^{-\left(\beta + \sum_{i=1}^n x_i\right)\lambda}\\
\end{align*}

On reconnaît là, à une constante (en $\lambda$) près la forme de la densité d'une loi Gamma de paramètres $\alpha + n$ et $\beta + \sum_{i=1}^n x_i$ : $\mathcal G(\alpha + n, \beta + \sum_{i=1}^n x_i)$.  
On remarque que nous sommes dans une situation de conjugaison.
:::
<br>
	