---
title: "Méta-analyses bayésienne"
linktitle: "Méta-analyses bayésienne"
date: "2020-11-30"
read_date: "2020-11-30"
menu:
  cours:
    parent: "IV Études de cas"
    weight: 2
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "01-slides"
output:
  blogdown::html_page:
    toc: true
---

### Introduction à la méta-analyse


Une méta-analyse est une analyse d'analyses, qui produit un seul et unique résumé quantitatif à partir d'un ensemble d'études répondant à une même question de recherche. Dans les applications biomédicales où les effets des thérapies sont souvent évalués dans plusieurs études différentes, cela peut se révéler particulièrement intéressant afin d'évaluer l'ensemble des preuves scientifiques disponibles sur une question précise. Idéalement, on regrouperait les observations individuelles de ces multiples études (tout en tenant compte des différences potentielles dans les expériences ainsi regroupées), mais, la plupart du temps, seules des estimations statistiques sommaires agrégées (souvent appelées tailles de l'effet) sont disponibles, ainsi que certaines mesures d'incertitude (généralement les erreurs types correspondantes).

#### Hétérogénéité entre études

Une des principales difficultés des méta-analyses est la variabilité des effets observés. Celle-ci peut soit venir de l'incertitude intra-étude, soit de la variabilité inter-études, c'est-à-dire d'une réelle hétérogénéité entre les différentes études regroupées. C'est généralement le cas lorsque différentes études ont été conduites au sein de populations différentes, ce qui ajoute donc une potentielle variabilité supplémentaire. De plus, les différentes études ont généralement des tailles d'échantillon variées, ce qui va nécessairement impacter l'estimation de l'effet étudié tout comme la précision associée.

#### Meta-analyse à effets aléatoires

Le modèle à effets aléatoires est l'une des approches les plus courante pour la méta-analyse. Ce modèle peut s'écrire ainsi :

$$y_i \sim \mathcal{N}(\theta_i, \sigma_i^2) $$
$$\theta_i \sim \mathcal{N}(\mu, \tau^2)$$

On peut l'envisager comme une généralisation hiérarchique du modèle à effet fixe $y_i \sim \mathcal{N}(\mu, \sigma_i^2)$, qui suppose lui le même effet moyen dans chaque étude inclus, tandis que le modèle à effets aléatoires permet de modéliser la variabilité entre études autour de cet effet moyen grâce au paramètre $\tau^2$ : $y_i \sim \mathcal{N}(\mu, \sigma_i^2 + \tau^2)$.



### La Méta-analyse en pratique

#### Méta-analyse : un cas d'usage parfait pour l'analyse bayésienne ?

L'approche bayésienne pour l'inférence statistique est très attractive dans ce contexte, en particulier lorsqu'une méta-analyse ne se base que sur un petit nombre d'études. En effet, l'approche bayésienne permet naturellement d'intégrer des connaissances antérieures sous la forme d'*a priori* informatifs, et peut pallier à certaines complications numériques rencontrées lors de l'analyse d'un nombre restreint d'observations.

#### Le *package* `r icon::fa_r_project(colour = "#0085d6")` `bayesmeta`


Le récent *package* `r icon::fa_r_project(colour = "#0085d6")` `bayesmeta` a été implémenté afin d'effectuer de telles méta-analyses bayésiennes. Une application `r icon::fa_r_project(colour = "#0085d6")` Shiny a également été développée et est disponible à l'url : http://ams.med.uni-goettingen.de:3838/bayesmeta/app/


### Jeu de données d'exemple : Crins *et al.*, 2014

En 2014, Crins *et al.*[@crins2014Interleukin2] ont publiés une méta-analyse d'essais contrôlés étudiant le traitement par récepteur antagonistes de l'interleukin-2 (IL-2RA) chez les enfants recevant une transplantation hépatique. Ils ont utilisé le modèle de méta-analyse à effets aléatoires afin d'estimer, entre autre,  l'incidence : i) du rejet sévère, ii) du rejet résistant aux stéroïdes, iii) de la lymphoprolifération post-transplantation, et iv) du décès (avec ou sans traitement par IL-2RA).


### Pour aller plus loin

#### Revue exhaustive de la littérature

Un travail très important préalable à toute méta-analyse est la recherche rigoureuse et exhaustive de la littérature scientifique. C'est un travail délicat, et des méthodologies et des outils spécifiques ont été développés. Un point important est que, bien souvent, les estimations et leurs erreurs types ne sont pas données explicitement, il faut donc les re-calculer soi-même à partir des informations disponibles dans les articles scientifiques.


#### Synthèse des preuves (*evidence synthesis*)

La méta-analyse est une des méthodes pour la synthèse des preuves, un domaine qui vise à synthétiser les connaissances scientifiques factuelles sur un sujet particulier. Par exemple, la méta-régression est une extension de la meta-analyse pour prendre en compte l'effet de covariables. D'autres approches, comme la modélisation mécaniste, peuvent également être envisagées pour la synthèse des données probantes (e.g. Commenges *et al.*, *LIDA*, 2012)[@commenges2013evidence].

La méta-analyse, et plus généralement les méthodes de synthèse des preuves font encore l'objet de recherches actives, et doivent être utilisées avec soin et réflexion. Par exemple, l'une des propriétés débattues du modèle à effets aléatoires est qu'il accordera effectivement moins de poids aux études dont l'échantillon est plus important (et dont les erreurs estimées autour des estimations sont mécaniquement plus petite --- Serghiou & Goodman, *JAMA*, 2018 [@serghiou2019RandomEffects]), ce qui peut être considéré soit comme un inconvénient (*bug*), soit comme un avantage (*feature*) selon le contexte (et en particulier selon la fiabilité de ces études).


